# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skaba', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='asd'),
            preserve_default=False,
        ),
    ]
