# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skaba', '0004_auto_20160807_1507'),
        ('skaba', '0004_auto_20160807_1624'),
    ]

    operations = [
    ]
