# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 17:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('skaba', '0004_auto_20160807_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 8, 7, 17, 5, 53, 218896, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
