# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skaba', '0005_merge'),
        ('skaba', '0005_event_date'),
    ]

    operations = [
    ]
