# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skaba', '0006_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='real_name',
        ),
    ]
