# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skaba', '0008_auto_20160815_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='guild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skaba.Guild'),
        ),
    ]
