# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skaba', '0006_auto_20160807_1902'),
        ('skaba', '0009_auto_20160815_1949'),
    ]

    operations = [
    ]
