# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-31 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skaba', '0010_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='user', max_length=9),
        ),
    ]
