# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-29 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skaba', '0011_auto_20160831_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guildpoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=1)),
                ('guild', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skaba.Guild')),
            ],
        ),
    ]
