# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-04 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skaba', '0012_guildpoints'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='eventdate',
        ),
    ]
